# Generated by Django 2.2.4 on 2019-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksinventory',
            name='price',
            field=models.FloatField(default=0, verbose_name='Book Price'),
        ),
    ]
