# Generated by Django 2.2.4 on 2019-08-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_booksinventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksinventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
